cd_platform:
    resource: "@CDPlatformBundle/Controller/"
    type:     annotation

cd_user:
    resource: "@CDUserBundle/Controller/"
    type:     annotation

logout:
    path: /logout

login_check:
    path: /login_check
