<?php

namespace CD\PlatformBundle\Repository;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends \Doctrine\ORM\EntityRepository
{

    public function getProjectsByLangs($uid, $langs)
	{
        $qb = $this->createQueryBuilder('p');

		$qb->select('p');

        $qb->where('p.user != :uid');
        $qb->andWhere('p.lang IN (:langs)');

        $qb->setParameter('uid', $uid);
        $qb->setParameter('langs', $langs);

        return $qb
            ->getQuery()
            ->getResult()
        ;
	}

}
