<?php

namespace CD\PlatformBundle\Repository;

/**
 * Traduction_TargetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Traduction_TargetRepository extends \Doctrine\ORM\EntityRepository
{
	public function countSourcesTranslatedByUserIdForProject($userId, $projectId)
	{
		return $this->createQueryBuilder('u')
		->select('COUNT(u)')
		->where('u.author = :uid')
        ->leftJoin('u.source', 'source')
        ->andWhere('source.project = :pid')
		->setParameter('uid', $userId)
        ->setParameter('pid', $projectId)
		->getQuery()
		->getSingleScalarResult();
	}
}
