<?php

namespace CD\PlatformBundle\Repository;

/**
 * Traduction_SourceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Traduction_SourceRepository extends \Doctrine\ORM\EntityRepository
{
}
