<?php

namespace CD\PlatformBundle\Repository;

/**
 * Traduction_TargetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Traduction_TargetRepository extends \Doctrine\ORM\EntityRepository
{
}
