<?php

namespace CD\PlatformBundle\Repository;

/**
 * Traduction_TargetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Traduction_TargetRepository extends \Doctrine\ORM\EntityRepository
{
	public function countAllSourcesTranslated()
	{
		return $this->createQueryBuilder('u')
		->select('COUNT(u)')
		->getQuery()
		->getSingleScalarResult();
	}

	public function countSourcesTranslatedByUserId($id)
	{
		return $this->createQueryBuilder('u')
		->select('COUNT(u)')
		->where('u.author = :id')
		->setParameter('id', $id)
		->getQuery()
		->getSingleScalarResult();
	}
}